init:
	terraform init

plan:
	terraform plan

apply:
	terraform apply

destoroy:
	terraform destroy

plan-var:
	terraform plan -var 'example_instance_type=t3.nano'

plan-var2:
	TF_VAR_example_instance_type=t3.nano terraform plan

prod-plan:
	terraform plan -var 'env=prod'
